version: '2'
services:
  security:
    build: ./
    ports:
     - "3000:3000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./
  db:
    build: ./docker/database-service